import './global.scss';
import Providers from '@/core/redux/rootProvider.component';
import PrimaryLayout from '@/core/layouts/PrimaryLayout/PrimaryLayout.component';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>
                <Providers>
                    <PrimaryLayout>{children}</PrimaryLayout>
                </Providers>
            </body>
        </html>
    );
}
